### ISSUE TITLE
react-refetch を置き換える

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#905]
フロントエンドとバックエンドの通信にはかつては react-refetch を使っていましたが、react-refetch がメンテされなそうということと、一部の `swr` による置き換えがうまくいっているので、残った react-refetch の実装も swr を中心としたものに置き換えていきます。

# Progress
- [x] TablePage by @Atsuyoshi-N (#951, #958)
- [x] ListPage  #1040
- [x] RecentContestList by @yb173 #1063 
- [x] RecentSubmissions by @yb173 #1065
- [ ] ContestUpdatePage
- [ ] SingleProblemList
- [ ] ResetProgress
- [ ] MyAccountPage
- [ ] UserProblemListPage

# フロントエンドの開発環境をセットアップする方法
https://github.com/kenkoooo/AtCoderProblems/tree/master/atcoder-problems-frontend
1. yarn をインストールする
2. yarn する
3. yarn start する

**Comment by Atsuyoshi-N** [comment]
私がこのissueを担当する予定です。
まずは、kenkooooさんとのやり取りで、TablePageの`submissions`を`useMultipleUserSubmissions`に変更するところから着手します。

**Comment by kenkoooo** [comment]
@Atsuyoshi-N ではまずは TablePage をお願いしますね

**Comment by kenkoooo** [comment]
分からないことがあればいつでもここに書いてください

**Comment by knagakura** [comment]
Webアプリ開発初心者ですが、参加させていただきます。よろしくお願いします！

**Comment by kenkoooo** [comment]
@knagakura お願いします。まずは  RecentContestList をお願いします。環境構築については上の方に書いてありますが、分からなければ聞いてください。やることは以下のとおりです。

1. [InternalAPIClient.ts](https://github.com/kenkoooo/AtCoderProblems/blob/0282bbde17f6b5628f3bb366fef2ac8cb2fca5f0/atcoder-problems-frontend/src/api/InternalAPIClient.ts) に最近のコンテストをreact-hookで取得する関数 `useRecentContests()` を追加する。
2. https://github.com/kenkoooo/AtCoderProblems/blob/0282bbde17f6b5628f3bb366fef2ac8cb2fca5f0/atcoder-problems-frontend/src/pages/Internal/VirtualContest/RecentContestList.tsx#L16
ここの部分を `useRecentContests` で置き換える。 

わからないことがあれば、どんなレベルでも構いませんので聞いてください。

**Comment by Atsuyoshi-N** [comment]
@kenkoooo 
お疲れ様です。大きく3点質問があります。

質問事項
useMultipleUserSubmissions(userId, rivals)を作成するにあたって、
- useSWRDataを使用することになると思いますが、第一引数のURLをuserIdごとに指定するにはどうしたら良いですか？
  - PromiseでuseSWRDataを囲もうと思ったのですが、それだと、レスポンスが返ってきたかが判断できなさそうだと思い混乱しています。
- fetcherには、既存の fetchUserSubmissions を使用すれば良いですか？
  - こちらの関数の中でfetchするURLを指定できればuseSWRDataの第一引数は特に気にしなくても良いですか？
- yarn start(react-scripts start)をしてブラウザで挙動を確認する時、コンソールにinternal server errorが出たときのエラーログの確認方法を教えていただきたいです。

**Comment by kenkoooo** [comment]
@Atsuyoshi-N 
- `useMultipleUserSubmissions` は既にあるのでそれを使ってください。上の方にある検索ボックスから検索できますのでご活用ください。
- バックエンドのログはAWSコンソールに入れば確認することは出来ますが、基本的にはフロントエンドで不正な引数でAPIを叩いていることが原因なので、まずはどのURLでどんな引数で叩いているかを教えてください。もしコードを読めるようでしたら実装は全てこのリポジトリにありますので探していただいても構いませんが、聞いていただくのが手っ取り早いかと思います。

**Comment by Atsuyoshi-N** [comment]
ありがとうございます。
`useMultipleUserSubmissions` を独自実装しようとしてつまづいていたのでアドバイス非常に助かりました。

TablePageを実装し、draft PRにしたのでお手隙で確認していただきたいです。

他のPageでも追加で実装が発生すると思ったのでdraft PRにしています。
TablePageで1 PRということであれば普通のPRに変更します。

**Comment by kenkoooo** [comment]
@Atsuyoshi-N TablePage で 1PRにしましょう

**Comment by Atsuyoshi-N** [comment]
@kenkoooo 1PRにしてdraftを外しました。お手隙で確認よろしくお願いします。

**Comment by kenkoooo** [comment]
@knagakura  調子はどうでしょう？とりあえずローカルで実行できましたか？

**Comment by Atsuyoshi-N** [comment]
@kenkoooo 
お疲れ様です。
もし次に取り組むタスクがあれば頂きたいです。

**Comment by kenkoooo** [comment]
@Atsuyoshi-N 

TablePage の react-refetch を置き換える作業をやっていただいても良いですか？まだ少し残っているかと思います。

**Comment by Atsuyoshi-N** [comment]
@kenkoooo 
`progressResetList` を置き換えるのに際して質問です。

前回のsubmissionsを取得するための関数は用意されていましたが、今回は、`APIClient.ts`に新たに足して対応するという理解で正しいですか？

**Comment by kenkoooo** [comment]
はい、たしかInternalAPIClient.tsみたいなのがあって、AtCoder Problems独自のデータに関してはこちらを使っているので、今回もこのファイルに足していただければと思います。

**Comment by kenkoooo** [comment]
@knagakura 連絡がつかないので一旦 unassign しておきますが、やりたくなったらいつでも言ってください！

**Comment by yb173** [comment]
@kenkoooo 
初めまして。
`RecentContestList` を担当してもよろしいでしょうか？

**Comment by kenkoooo** [comment]
@yb173 ぜひ！分からないことがあればいつでも聞いてください！

**Comment by yb173** [comment]
@kenkoooo 
順番前後しますが、次は `RecentSubmissions` を担当してもよろしいですか？

**Comment by kenkoooo** [comment]
@yb173 ぜひ〜〜〜

**Comment by kenkoooo** [comment]
@

**Comment by kenkoooo** [comment]
@atsuya02 `yarn start` でローカルで走るのはできていますか？

**Comment by atsuya02** [comment]
@kenkoooo 
`yarn start`でローカルで走るのはできています。
ログインをしておらず、`Create New Contest`ボタンが表示されていませんでした。
解決しました、申し訳ありません！

**Comment by kenkoooo** [comment]
良かったです！

**Comment by atsuya02** [comment]
@kenkoooo 
` SingleProblemList`を担当してもよろしいでしょうか？

**Comment by kenkoooo** [comment]
@atsuya02 ぜひ！

**Comment by atsuya02** [comment]
@kenkoooo 
`ResetProgress`を担当してもよろしいでしょうか？

**Comment by kenkoooo** [comment]
@atsuya02 ぜひ！

**Comment by atsuya02** [comment]
@kenkoooo 
`MyAccountPage`を担当してもいいですか？

**Comment by kenkoooo** [comment]
@atsuya02 ぜひ！
