### ISSUE TITLE
ランキング情報を取れる API を作る。

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#945]
現状のランキングは全てのランキング情報を返していますが、これはそろそろデータ転送料的に厳しくなってきたので、以下の2つのAPIに分割したいです。

# 「上位x位からy位までを取得」というクエリーに答えるAPI

例えば、ACランキング上位301〜400位を表示するSQLは以下のように書けます。
```sql
SELECT * FROM accepted_count 
ORDER BY problem_count DESC, user_id 
OFFSET 300 LIMIT 100;
```

# ユーザー名を指定した時にその順位を返すAPI

例えば、ユーザー 'kenkoooo' のAC数ランキングは以下のSQLで取得できます。
```sql
SELECT COUNT(*) FROM accepted_count 
WHERE problem_count > (
    SELECT problem_count FROM accepted_count
    WHERE user_id='kenkoooo'
)
```

# Progress
- AC数ランキング
  - [x] sql-client (上位N件) by @cupro29 #949 
  - [x] server (上位N件) by @cupro29  #956
  - [x] server (ユーザーの順位) by @cupro29 #986
  - [x] API doc  (上位N件) #966 
  - [x] front-end #1012 
- Rated Poin Sum ランキング
  - [x] sql-client (上位N件) by @komorin95 #950
  - [x] server (上位N件) by @hotate29 #982 
  - [x] server (ユーザーの順位) by @hotate29 #1014 
  - [x] API doc #1032 
  - [x] front-end #1036 
- 言語別AC数ランキング
  - [x] sql-client (上位N件) #985
  - [x] sql-client (ユーザーの言語ごとの順位) by @fukatani #987 
  - [x] server  #985
  - [x] API doc #1003
  - [x] front-end #1009 
- Streakランキング
  - [x] sql-client by @nebocco  #973
  - [x] server @nebocco #975
  - [x] API doc #980
  - [x] front-end by @fukatani #1023

**Comment by kenkoooo** [comment]
@cupro29 1つめの「上位x位からy位までを取得」というクエリーに答えるAPIをお願いしても良いですか？

**Comment by cupro29** [comment]
はい。
具体的にはどうすれば良いでしょうか？

**Comment by kenkoooo** [comment]
@cupro29 https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/sql-client/src/accepted_count.rs にAC数ランキング関連の実装がまとまっているので、そこに関数を追加します。作業としては以下のとおりです。

1. https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/sql-client/src/accepted_count.rs に「上位x位からy位までを取得」する関数を追加する。
2. https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/sql-client/tests/test_accepted_count.rs にそのテストを追加する。
3. 一旦ここまででプルリクを作る。
3. サーバー側から実装した関数を呼び出すようにする。そのテストも追加する。
4. （できたら）ブラウザ側から呼び出す API を新しいものに切り替える。

**Comment by kenkoooo** [comment]
@komorin95 「上位x位からy位までを取得」というクエリーに答えるAPIのrated point sumランキングをやっていただいても良いですか？

**Comment by kenkoooo** [comment]
@wakuwinmail 「上位x位からy位までを取得」というクエリーに答えるAPIの言語別 AC 数ランキングをやっていただいても良いですか？

**Comment by komorin95** [comment]
> 
> 
> @komorin95 「上位x位からy位までを取得」というクエリーに答えるAPIのrated point sumランキングをやっていただいても良いですか？

OKです！cupro29さん宛てのコメントでされた説明も参考にしつつやってみます。

**Comment by kenkoooo** [comment]
@cupro29 @komorin95 
`sql-client` の機能追加ありがとうございました。次のステップとして、今度は実装した機能を RESTful API としてサーバーサイドに実装します。こうすることでブラウザ側から呼び出すことができるようになります。

手順としては以下のとおりです。
1. [/src/server](https://github.com/kenkoooo/AtCoderProblems/tree/master/atcoder-problems-backend/src/server) 内にファイルを作り、そこに関数を実装します。(参考: [/src/server/problem_list.rs](https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/src/server/problem_list.rs))
2. サーバーに組み入れます: [server/mod.rs](https://github.com/kenkoooo/AtCoderProblems/blob/70a48cda2ada4071cafb7b1045248aa25c6fc7a3/atcoder-problems-backend/src/server/mod.rs#L37)
3. テストを書きます。 (参考: [/tests/test_server_e2e_problem_list.rs](https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/tests/test_server_e2e_problem_list.rs))

分からないことがあったらいつでもどんなレベルでもいいので聞いてください。とりあえず書いていただければ、PR 上で見せていただくので、まずは細かいことは気にしなくて大丈夫です。

**Comment by kenkoooo** [comment]
@wakuwinmail 調子はどうですか？「何が分からないか分からない」という状態でも良いので、詰まっていたらいつでもここに書いてください。

**Comment by wakuwinmail** [comment]
> @wakuwinmail 調子はどうですか？「何が分からないか分からない」という状態でも良いので、詰まっていたらいつでもここに書いてください。

来週いっぱいくらいまで用事が重なっているためまだ手を付けていない状態です。また取り組んで分からないことがあれば書き込みさせていただきます。

**Comment by kenkoooo** [comment]
@wakuwinmail 了解です！

**Comment by kenkoooo** [comment]
@cupro29 おつかれさまでした！もし興味があれば他にやることはあるので、またいつでもお声がけください！

**Comment by kenkoooo** [comment]
@wakuwinmail 忙しそうなので一旦 unassign しておきますが、やりたくなったらいつでも言ってください！

**Comment by hotate29** [comment]
@kenkoooo こんばんは。Rustはかじってちょっと飲み込んだ程度なんですが、何かお手伝いできませんか？

**Comment by kenkoooo** [comment]
> @kenkoooo こんばんは。Rustはかじってちょっと飲み込んだ程度なんですが、何かお手伝いできませんか？

最初にやるのに丁度よさそうなところですと、 #950 で Rated Point Sum の x 位〜 y 位を取得する関数を実装したので、それを #956 の要領で server 上に実装するというのがあります。

**Comment by hotate29** [comment]
それやりたいです。ある程度完成したらプルリクを作る感じで良いですか？

**Comment by kenkoooo** [comment]
> それやりたいです。ある程度進捗ができたらプルリクを作る感じで良いですか？

はい、お願いします。まず最初は以下の要領で開発環境のセットアップが必要かと思われます。

- dockerとdocker-compose をインストール
- https://github.com/kenkoooo/AtCoderProblems/blob/master/atcoder-problems-backend/README.md#test を実行してテストが全て通ることを確認する

何かわからないことや謎エラーで詰まったことなどがあれば、どんなレベルでも大丈夫なので聞いてください。

**Comment by fukatani** [comment]
私もどこかお手伝いできるところあったら入りたいです！

**Comment by kenkoooo** [comment]
@fukatani お願いします！

具体的に残っていることは上の方のチェックリストに書いてありますが、だいたい以下のようなものが残っています。
- ユーザー名を渡したらAC数とランクを返してくれるAPI
- ユーザー名を渡したらRated Point Sumやランクを返してくれるAPI
-  言語別AC数に関するAPI（手付かず）
- フロントエンドで、既存のランキング表示機能やユーザーページのランク表示機能を新しいAPIを使うように更新する

**Comment by cupro29** [comment]
@kenkoooo 手が空いたので何かお手伝いをしたいです。
「ユーザー名を渡したらAC数とランクを返してくれるAPI」をやってもいいですか？

**Comment by fukatani** [comment]
@kenkoooo 
ユーザー名を渡したらRated Point Sumやランクを返してくれるAPI、やります！

**Comment by kenkoooo** [comment]
> @kenkoooo 手が空いたので何かお手伝いをしたいです。
> 「ユーザー名を渡したらAC数とランクを返してくれるAPI」をやってもいいですか？

お願いします！

**Comment by kenkoooo** [comment]
> @kenkoooo
> ~ユーザー名を渡したらRated Point Sumやランクを返してくれるAPI、やります！~
> 言語別AC数のAPIやります！
> 
> 言語ごとのユーザーのAC数上位x位からy位を返す形でいいですか？
> x, yだけ指定して、言語は毎回全言語返すと思っているのですが、、
> 
> ```
> {
>     'cpp': ["kmjp", ...],
>     'python': ["maspy", ...],
> }
> ```
> 
> というようなレスポンスです。
> まずはsql_clientから作ってPR開きます。

言語を指定するとそれの上位x位からy位を返すのを考えていましたが、冷静に考えてみると言語を引数として受け取るの険しさがありますね……

**Comment by kenkoooo** [comment]
> 言語を指定するとそれの上位x位からy位を返すのを考えていましたが、冷静に考えてみると言語を引数として受け取るの険しさがありますね……

言語を受け取ってランキングを返す形式でも、言語一覧が取れる API を別に提供するなら良さそうという気持ちになりました。

**Comment by fukatani** [comment]
@kenkoooo 
フロントエンドもやってみたいです。
LanguageOwnerをAPI使って実装すればいいでしょうか？

**Comment by hotate29** [comment]
ユーザーのRated Point Sumランキングを取得するsql-clientをやりたいです

**Comment by kenkoooo** [comment]
@fukatani お願いします！ちょっと忙しくてデプロイとかもろもろ間に合っていなくて申し訳ないです…

**Comment by kenkoooo** [comment]
@hotate29 お願いします！ちょっとissueの更新が間に合っていないので、既に入っているような気もするのですが、もしまだ入ってなかったら是非やってみてください。

**Comment by hotate29** [comment]
@kenkoooo ユーザーのRated Point Sumを取得する関数と、そのRPSが何位かを取得する関数が既にあるのですが、これらを使うか普通にSQLを書くかで若干迷っています

https://github.com/kenkoooo/AtCoderProblems/blob/f246de3043fbbcc82cc74d7a5a9a57e76d6fdaac/atcoder-problems-backend/sql-client/src/rated_point_sum.rs#L94-L111

**Comment by fukatani** [comment]
@kenkoooo 
いえいえ、いつも丁寧にレビューしてくださりありがとうございます。
kenkooooさんのペースで進めれば大丈夫です。
フロントエンドのコードの理解に時間かかりそうなので、私もゆっくり実装を考えてみます。

**Comment by kenkoooo** [comment]
@hotate29 すみません、見たらもう既に入っていましたね。issue の方更新しておきます。

**Comment by fukatani** [comment]
ちょっとご相談させてほしいです。
`useLangRanking`を書き直すためにlanguage_listのAPIから得た各言語のリストからそれぞれのランキングをfetchしてマージしようと以下のコードを書きました。

```typescript
export const useLangRanking = () => {
  const url = `${ATCODER_API_URL}/language_list`;
  const languages =
    useSWR(url, (url) => fetchTypedArray(url, isString))?.data ?? [];
  languages.map((language) => {
    const url = `${ATCODER_API_URL}/language_reserved/${language}`;
    const items =
      useSWR(url, (url) => fetchTypedArray(url, isLangRankingEntry))?.data ??
      [];
    // merge results
  });
 };
```
すると、
```
ESLint: React Hook "useSWR" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function
```
というエラーが出ます。Reactの制約でmap関数のコールバックやfor文の中で`useSWR`やそのラッパーである`useSWRData`をコールすることができないようです。
自分でも調べていますが、これを回避する方法ご存じの方いましたら、お助けください。

**Comment by kenkoooo** [comment]
@fukatani 

結論から言いますと、次のような形になるのかな、と思います。

```jsx
const LanguageRankings = () => {
  const languages = useLanguages();
  return {languages.map(language => <SingleLanguageRanking language={language} />)};
};

const SingleLanguageRanking = (props) => {
  const ranking = useLanguageRanking(props.language);
  return ...
};
```

**Comment by kenkoooo** [comment]
`useSWR` はあくまでもキャッシュするための関数ですので、挙げていただいたような方法でやるのでしたら、以下のようになりますかね。

```typescript
const fetcher = () =>{
 const languages = fetch(language_list_api);
 return languages.map(language => fetch(language_ranking_api, language));
};

const useAllLanguageRankings = () => {
  return useSWR(language_ranking_unique_key, fetcher);
};
```

**Comment by fukatani** [comment]
@kenkoooo 
ACランキングのフロントエンドも検討してみますね。

**Comment by fukatani** [comment]
@kenkoooo 
ACランキングって上位1000名とかしか表示・検索できない、みたいな仕様に変更することになりますか？
今のまま全順位から表示も検索できるとなると結局ランキング全てを通信しないと実現できないように思うので。

ランキングは1000名も表示できれば十分でしょうし、ユーザー名を検索してランキングを得ることはユーザーページでもできるので問題ないかなと考えています。

**Comment by kenkoooo** [comment]
表示はページネーションをちゃんと実装すれば1000以降も実装できるはずですが、上位1000だけでも良いと思います。検索はまあ無理なので削除しましょう。

**Comment by fukatani** [comment]
わかりました！
検索もないのに、1000もページを見ていくことはあまりない気もするので、ここは楽することをまずは考えます。

**Comment by fukatani** [comment]
@kenkoooo 
相談があります。

https://kenkoooo.com/atcoder/resources/ac.json
が
```json
[{"user_id":"aa","problem_count":2}, ...]
```
というような形式で返しているのに対し、新しいAPI　https://kenkoooo.com/atcoder/atcoder-api/v3/ac_ranking?from=0&to=10　は

```json
[{"user_id":"aa","count":2}, ...]
```
とプロパティの名前が`problem_count` -> `count`に名前が変わっていることに気づきました。
一方で、language count ( https://kenkoooo.com/atcoder/atcoder-api/v3/language_ranking?from=0&to=10&language=Rust ) はまだ`problem_count`を使っています。私が実装しましたが、無頓着でした。。

API公開後になってしまったんですけど、今からでも統一したほうがいいのかなと思いましたが、どうでしょうか？
また、その場合、どちらに合わせるべきでしょうか？

**Comment by kenkoooo** [comment]
> @kenkoooo
> 相談があります。
> 
> https://kenkoooo.com/atcoder/resources/ac.json
> が
> 
> ```json
> [{"user_id":"aa","problem_count":2}, ...]
> ```
> 
> というような形式で返しているのに対し、[新しいAPI](https://kenkoooo.com/atcoder/atcoder-api/v3/ac_ranking?from=0&to=10)は
> 
> ```json
> [{"user_id":"aa","count":2}, ...]
> ```
> 
> とプロパティの名前が`problem_count` -> `count`に名前が変わっていることに気づきました。
> 一方で、[language count](https://kenkoooo.com/atcoder/atcoder-api/v3/language_ranking?from=0&to=10&language=Rust) はまだ`problem_count`を使っています。language countは私が実装しましたが、無頓着でした。。
> 
> API公開後になってしまったんですけど、今からでも統一したほうがいいのかなと思いましたが、どうでしょうか？
> [https://github.com/kenkoooo/AtCoderProblems/pull/988で`count`に変えているようですが、意図的に以前と変えたということですよね。](https://github.com/kenkoooo/AtCoderProblems/pull/988%E3%81%A7%60count%60%E3%81%AB%E5%A4%89%E3%81%88%E3%81%A6%E3%81%84%E3%82%8B%E3%82%88%E3%81%86%E3%81%A7%E3%81%99%E3%81%8C%E3%80%81%E6%84%8F%E5%9B%B3%E7%9A%84%E3%81%AB%E4%BB%A5%E5%89%8D%E3%81%A8%E5%A4%89%E3%81%88%E3%81%9F%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8%E3%81%A7%E3%81%99%E3%82%88%E3%81%AD%E3%80%82)
> 
> フロントエンド書いてたら、`IsRankingEntry`などの関数、interfaceがそのまま使えなくて、少しもったいない状況です。

多分どちらでも良いのですが、`problem_count` よりも `count` の方がデータ転送料が少しだけ安くなるとかありませんかね（gzip圧縮されるので大して変わらないかもしれません）

**Comment by fukatani** [comment]
@kenkoooo 
では`count`に統一するPR入れます。
problem_と付けなくても十分内容はわかりますし。

**Comment by fukatani** [comment]
streak rankingのフロントエンド、他に人いなければ着手します!

**Comment by kenkoooo** [comment]
@fukatani お願いします！

**Comment by fukatani** [comment]
クローズさせちゃったほうがいいと思うので、残るRPSのフロントエンドも他に人いなければ着手しますね。

**Comment by kenkoooo** [comment]
おつかれさまでした〜
