### ISSUE TITLE
提出の一部を取得できる API を作る

### ISSUE THREAD

**Issue by kenkoooo** [kenkoooo/AtCoderProblems#948]
現在の提出 API はユーザー名を指定するとそのユーザーの提出を全て返します。ブラウザ側で既に受け取った提出を保存しておき、差分のみを受け取るようにすることができれば、データ転送料を削減することができそうです。[ユーザー名, 時刻] を受け取り、指定されたユーザーの指定された時刻以降の提出を返すAPIを作ることで実現を目指します。

- [x] sql-client に実装する (#952)
- [x] REST endpoint を作る (#955, #960)
- [x] API Document を更新する (#962)

**Comment by tsutaj** [comment]
内容について質問があります。

> ブラウザ側で既に受け取った提出を保存しておき

これは、ユーザーが最後に API を叩いた時刻自体と、その時刻以前の (json などの) 情報をブラウザに覚えさせておく、ということでしょうか？

**Comment by kenkoooo** [comment]
@tsutaj 
ブラウザにはIndexedDBという仕組みがあるので、それを使うのが良いのではないかと思っています。取得した時刻は保存しておく必要はなく、ブラウザDBに保存されているそのユーザーの提出のうち一番新しいもの以降のものを取得するようにするのが良いと思ってます。

**Comment by kenkoooo** [comment]
このissueではブラウザ側（フロントエンド）の実装は置いておいて、まずはサーバーサイドの方をやります。

**Comment by tsutaj** [comment]
なるほど、理解できました。

実際に実装に取り掛かれるのは明日以降になりそうなので、疑問点があれば明日以降にまた連絡いたします。

**Comment by kenkoooo** [comment]
フロントエンド側については新しく #963 を切ったので、これは close します。
@tsutaj おつかれさまでした！
